/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DeploymentLocationLocationCode implements EnumType {

    da("da"),

    testbed("testbed"),

    staging("staging"),

    production("production");

    private final String literal;

    private DeploymentLocationLocationCode(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "deployment_location_location_code";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
