/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema;


import hms.commons.rnm.db.schema.tables.Customer;
import hms.commons.rnm.db.schema.tables.CustomerModuleDeployment;
import hms.commons.rnm.db.schema.tables.DaReleaseNote;
import hms.commons.rnm.db.schema.tables.DeploymentLocation;
import hms.commons.rnm.db.schema.tables.DevReleaseNote;
import hms.commons.rnm.db.schema.tables.FlywaySchemaHistory;
import hms.commons.rnm.db.schema.tables.Module;
import hms.commons.rnm.db.schema.tables.ModuleDependency;
import hms.commons.rnm.db.schema.tables.ModuleDeployments;
import hms.commons.rnm.db.schema.tables.ModuleTag;
import hms.commons.rnm.db.schema.tables.ReleaseNote;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>customer_module_deployment</code>.
     */
    public final CustomerModuleDeployment CUSTOMER_MODULE_DEPLOYMENT = CustomerModuleDeployment.CUSTOMER_MODULE_DEPLOYMENT;

    /**
     * The table <code>da_release_note</code>.
     */
    public final DaReleaseNote DA_RELEASE_NOTE = DaReleaseNote.DA_RELEASE_NOTE;

    /**
     * The table <code>deployment_location</code>.
     */
    public final DeploymentLocation DEPLOYMENT_LOCATION = DeploymentLocation.DEPLOYMENT_LOCATION;

    /**
     * The table <code>dev_release_note</code>.
     */
    public final DevReleaseNote DEV_RELEASE_NOTE = DevReleaseNote.DEV_RELEASE_NOTE;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>module</code>.
     */
    public final Module MODULE = Module.MODULE;

    /**
     * The table <code>module_dependency</code>.
     */
    public final ModuleDependency MODULE_DEPENDENCY = ModuleDependency.MODULE_DEPENDENCY;

    /**
     * The table <code>module_deployments</code>.
     */
    public final ModuleDeployments MODULE_DEPLOYMENTS = ModuleDeployments.MODULE_DEPLOYMENTS;

    /**
     * The table <code>module_tag</code>.
     */
    public final ModuleTag MODULE_TAG = ModuleTag.MODULE_TAG;

    /**
     * The table <code>release_note</code>.
     */
    public final ReleaseNote RELEASE_NOTE = ReleaseNote.RELEASE_NOTE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            CustomerModuleDeployment.CUSTOMER_MODULE_DEPLOYMENT,
            DaReleaseNote.DA_RELEASE_NOTE,
            DeploymentLocation.DEPLOYMENT_LOCATION,
            DevReleaseNote.DEV_RELEASE_NOTE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Module.MODULE,
            ModuleDependency.MODULE_DEPENDENCY,
            ModuleDeployments.MODULE_DEPLOYMENTS,
            ModuleTag.MODULE_TAG,
            ReleaseNote.RELEASE_NOTE);
    }
}
