/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema;


import hms.commons.rnm.db.schema.tables.Customer;
import hms.commons.rnm.db.schema.tables.CustomerModuleDeployment;
import hms.commons.rnm.db.schema.tables.DaReleaseNote;
import hms.commons.rnm.db.schema.tables.DeploymentLocation;
import hms.commons.rnm.db.schema.tables.DevReleaseNote;
import hms.commons.rnm.db.schema.tables.FlywaySchemaHistory;
import hms.commons.rnm.db.schema.tables.Module;
import hms.commons.rnm.db.schema.tables.ModuleDependency;
import hms.commons.rnm.db.schema.tables.ModuleDeployments;
import hms.commons.rnm.db.schema.tables.ModuleTag;
import hms.commons.rnm.db.schema.tables.ReleaseNote;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>customer_module_deployment</code>.
     */
    public static final CustomerModuleDeployment CUSTOMER_MODULE_DEPLOYMENT = CustomerModuleDeployment.CUSTOMER_MODULE_DEPLOYMENT;

    /**
     * The table <code>da_release_note</code>.
     */
    public static final DaReleaseNote DA_RELEASE_NOTE = DaReleaseNote.DA_RELEASE_NOTE;

    /**
     * The table <code>deployment_location</code>.
     */
    public static final DeploymentLocation DEPLOYMENT_LOCATION = DeploymentLocation.DEPLOYMENT_LOCATION;

    /**
     * The table <code>dev_release_note</code>.
     */
    public static final DevReleaseNote DEV_RELEASE_NOTE = DevReleaseNote.DEV_RELEASE_NOTE;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>module</code>.
     */
    public static final Module MODULE = Module.MODULE;

    /**
     * The table <code>module_dependency</code>.
     */
    public static final ModuleDependency MODULE_DEPENDENCY = ModuleDependency.MODULE_DEPENDENCY;

    /**
     * The table <code>module_deployments</code>.
     */
    public static final ModuleDeployments MODULE_DEPLOYMENTS = ModuleDeployments.MODULE_DEPLOYMENTS;

    /**
     * The table <code>module_tag</code>.
     */
    public static final ModuleTag MODULE_TAG = ModuleTag.MODULE_TAG;

    /**
     * The table <code>release_note</code>.
     */
    public static final ReleaseNote RELEASE_NOTE = ReleaseNote.RELEASE_NOTE;
}
