version: '3.7'

services:
  ##db
  rnm_db:
    image: rnm/mysql
    build:
      context: ../db-scripts
      dockerfile: Dockerfile.dev
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${MYSQL_DATA_VOLUME}:/var/lib/mysql
    networks:
      rnmmesh:
        aliases:
          - rnm-mysql
    restart: always
    ports:
      - 33080:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: release_note_db
      TZ: ${SERVER_TIME_ZONE}

  #keycloack
  rnm_keycloak:
    build:
      context: ../keycloak
      dockerfile: Dockerfile.dev
    ports:
      - 9090:8080
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
#      DB_VENDOR: MYSQL
#      DB_ADDR: rnm-mysql
#      DB_PORT: 3306
#      DB_DATABASE: keycloak
#      DB_USER: user
#      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: test123#
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      TZ: ${SERVER_TIME_ZONE}
    volumes:
      - ${PORTAL_KEYCLOAK_REALM_FILE_PATH}:/tmp/realm-export.json
#      - ${PORTAL_KEYCLOAK_LOGIN_THEME_FILE_PATH}:/opt/jboss/keycloak/themes/portal-theme
    #      - ../init/keycloak/loginTheme:/opt/jboss/keycloak/themes/loginTheme
    #      - /hms/logs-docker/keycloak/:/opt/jboss/keycloak/standalone/log
    depends_on:
      - rnm_db
    restart: always
    networks:
      rnmmesh:
        aliases:
          - rnm-keycloak

networks:
  rnmmesh: {}
