/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables.records;


import hms.commons.rnm.db.schema.tables.DaReleaseNote;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DaReleaseNoteRecord extends UpdatableRecordImpl<DaReleaseNoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>da_release_note.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>da_release_note.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>da_release_note.tag_id</code>.
     */
    public void setTagId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>da_release_note.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>da_release_note.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>da_release_note.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>da_release_note.artifact_location</code>.
     */
    public void setArtifactLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>da_release_note.artifact_location</code>.
     */
    public String getArtifactLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>da_release_note.mdsum</code>.
     */
    public void setMdsum(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>da_release_note.mdsum</code>.
     */
    public String getMdsum() {
        return (String) get(4);
    }

    /**
     * Setter for <code>da_release_note.tested_areas</code>.
     */
    public void setTestedAreas(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>da_release_note.tested_areas</code>.
     */
    public String getTestedAreas() {
        return (String) get(5);
    }

    /**
     * Setter for <code>da_release_note.new_features</code>.
     */
    public void setNewFeatures(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>da_release_note.new_features</code>.
     */
    public String getNewFeatures() {
        return (String) get(6);
    }

    /**
     * Setter for <code>da_release_note.found_bugs</code>.
     */
    public void setFoundBugs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>da_release_note.found_bugs</code>.
     */
    public String getFoundBugs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>da_release_note.fixed_bugs</code>.
     */
    public void setFixedBugs(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>da_release_note.fixed_bugs</code>.
     */
    public String getFixedBugs() {
        return (String) get(8);
    }

    /**
     * Setter for <code>da_release_note.know_bugs</code>.
     */
    public void setKnowBugs(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>da_release_note.know_bugs</code>.
     */
    public String getKnowBugs() {
        return (String) get(9);
    }

    /**
     * Setter for <code>da_release_note.limitations</code>.
     */
    public void setLimitations(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>da_release_note.limitations</code>.
     */
    public String getLimitations() {
        return (String) get(10);
    }

    /**
     * Setter for <code>da_release_note.modules_released</code>.
     */
    public void setModulesReleased(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>da_release_note.modules_released</code>.
     */
    public String getModulesReleased() {
        return (String) get(11);
    }

    /**
     * Setter for <code>da_release_note.prerequisits</code>.
     */
    public void setPrerequisits(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>da_release_note.prerequisits</code>.
     */
    public String getPrerequisits() {
        return (String) get(12);
    }

    /**
     * Setter for <code>da_release_note.deploy_instructions</code>.
     */
    public void setDeployInstructions(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>da_release_note.deploy_instructions</code>.
     */
    public String getDeployInstructions() {
        return (String) get(13);
    }

    /**
     * Setter for <code>da_release_note.patch_instructions</code>.
     */
    public void setPatchInstructions(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>da_release_note.patch_instructions</code>.
     */
    public String getPatchInstructions() {
        return (String) get(14);
    }

    /**
     * Setter for <code>da_release_note.areas_to_be_tested</code>.
     */
    public void setAreasToBeTested(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>da_release_note.areas_to_be_tested</code>.
     */
    public String getAreasToBeTested() {
        return (String) get(15);
    }

    /**
     * Setter for <code>da_release_note.released_date</code>.
     */
    public void setReleasedDate(LocalDate value) {
        set(16, value);
    }

    /**
     * Getter for <code>da_release_note.released_date</code>.
     */
    public LocalDate getReleasedDate() {
        return (LocalDate) get(16);
    }

    /**
     * Setter for <code>da_release_note.released_by</code>.
     */
    public void setReleasedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>da_release_note.released_by</code>.
     */
    public String getReleasedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>da_release_note.tested_by</code>.
     */
    public void setTestedBy(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>da_release_note.tested_by</code>.
     */
    public String getTestedBy() {
        return (String) get(18);
    }

    /**
     * Setter for <code>da_release_note.test_cases</code>.
     */
    public void setTestCases(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>da_release_note.test_cases</code>.
     */
    public String getTestCases() {
        return (String) get(19);
    }

    /**
     * Setter for <code>da_release_note.planned_start</code>.
     */
    public void setPlannedStart(LocalDate value) {
        set(20, value);
    }

    /**
     * Getter for <code>da_release_note.planned_start</code>.
     */
    public LocalDate getPlannedStart() {
        return (LocalDate) get(20);
    }

    /**
     * Setter for <code>da_release_note.planned_end</code>.
     */
    public void setPlannedEnd(LocalDate value) {
        set(21, value);
    }

    /**
     * Getter for <code>da_release_note.planned_end</code>.
     */
    public LocalDate getPlannedEnd() {
        return (LocalDate) get(21);
    }

    /**
     * Setter for <code>da_release_note.actual_start</code>.
     */
    public void setActualStart(LocalDate value) {
        set(22, value);
    }

    /**
     * Getter for <code>da_release_note.actual_start</code>.
     */
    public LocalDate getActualStart() {
        return (LocalDate) get(22);
    }

    /**
     * Setter for <code>da_release_note.actual_end</code>.
     */
    public void setActualEnd(LocalDate value) {
        set(23, value);
    }

    /**
     * Getter for <code>da_release_note.actual_end</code>.
     */
    public LocalDate getActualEnd() {
        return (LocalDate) get(23);
    }

    /**
     * Setter for <code>da_release_note.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(24, value);
    }

    /**
     * Getter for <code>da_release_note.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>da_release_note.last_updated_time</code>.
     */
    public void setLastUpdatedTime(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>da_release_note.last_updated_time</code>.
     */
    public LocalDateTime getLastUpdatedTime() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>da_release_note.type</code>.
     */
    public void setType(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>da_release_note.type</code>.
     */
    public String getType() {
        return (String) get(26);
    }

    /**
     * Setter for <code>da_release_note.comment</code>.
     */
    public void setComment(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>da_release_note.comment</code>.
     */
    public String getComment() {
        return (String) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DaReleaseNoteRecord
     */
    public DaReleaseNoteRecord() {
        super(DaReleaseNote.DA_RELEASE_NOTE);
    }

    /**
     * Create a detached, initialised DaReleaseNoteRecord
     */
    public DaReleaseNoteRecord(Integer id, Integer tagId, Integer customerId, String artifactLocation, String mdsum, String testedAreas, String newFeatures, String foundBugs, String fixedBugs, String knowBugs, String limitations, String modulesReleased, String prerequisits, String deployInstructions, String patchInstructions, String areasToBeTested, LocalDate releasedDate, String releasedBy, String testedBy, String testCases, LocalDate plannedStart, LocalDate plannedEnd, LocalDate actualStart, LocalDate actualEnd, LocalDateTime createdDate, LocalDateTime lastUpdatedTime, String type, String comment) {
        super(DaReleaseNote.DA_RELEASE_NOTE);

        setId(id);
        setTagId(tagId);
        setCustomerId(customerId);
        setArtifactLocation(artifactLocation);
        setMdsum(mdsum);
        setTestedAreas(testedAreas);
        setNewFeatures(newFeatures);
        setFoundBugs(foundBugs);
        setFixedBugs(fixedBugs);
        setKnowBugs(knowBugs);
        setLimitations(limitations);
        setModulesReleased(modulesReleased);
        setPrerequisits(prerequisits);
        setDeployInstructions(deployInstructions);
        setPatchInstructions(patchInstructions);
        setAreasToBeTested(areasToBeTested);
        setReleasedDate(releasedDate);
        setReleasedBy(releasedBy);
        setTestedBy(testedBy);
        setTestCases(testCases);
        setPlannedStart(plannedStart);
        setPlannedEnd(plannedEnd);
        setActualStart(actualStart);
        setActualEnd(actualEnd);
        setCreatedDate(createdDate);
        setLastUpdatedTime(lastUpdatedTime);
        setType(type);
        setComment(comment);
    }
}
