/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables.records;


import hms.commons.rnm.db.schema.enums.DeploymentLocationLocationCode;
import hms.commons.rnm.db.schema.tables.DeploymentLocation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeploymentLocationRecord extends UpdatableRecordImpl<DeploymentLocationRecord> implements Record4<Integer, DeploymentLocationLocationCode, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>deployment_location.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>deployment_location.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>deployment_location.location_code</code>.
     */
    public void setLocationCode(DeploymentLocationLocationCode value) {
        set(1, value);
    }

    /**
     * Getter for <code>deployment_location.location_code</code>.
     */
    public DeploymentLocationLocationCode getLocationCode() {
        return (DeploymentLocationLocationCode) get(1);
    }

    /**
     * Setter for <code>deployment_location.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>deployment_location.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>deployment_location.last_updated_time</code>.
     */
    public void setLastUpdatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>deployment_location.last_updated_time</code>.
     */
    public LocalDateTime getLastUpdatedTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, DeploymentLocationLocationCode> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, DeploymentLocationLocationCode, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, DeploymentLocationLocationCode, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DeploymentLocation.DEPLOYMENT_LOCATION.CUSTOMER_ID;
    }

    @Override
    public Field<DeploymentLocationLocationCode> field2() {
        return DeploymentLocation.DEPLOYMENT_LOCATION.LOCATION_CODE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return DeploymentLocation.DEPLOYMENT_LOCATION.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return DeploymentLocation.DEPLOYMENT_LOCATION.LAST_UPDATED_TIME;
    }

    @Override
    public Integer component1() {
        return getCustomerId();
    }

    @Override
    public DeploymentLocationLocationCode component2() {
        return getLocationCode();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdatedTime();
    }

    @Override
    public Integer value1() {
        return getCustomerId();
    }

    @Override
    public DeploymentLocationLocationCode value2() {
        return getLocationCode();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdatedTime();
    }

    @Override
    public DeploymentLocationRecord value1(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public DeploymentLocationRecord value2(DeploymentLocationLocationCode value) {
        setLocationCode(value);
        return this;
    }

    @Override
    public DeploymentLocationRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public DeploymentLocationRecord value4(LocalDateTime value) {
        setLastUpdatedTime(value);
        return this;
    }

    @Override
    public DeploymentLocationRecord values(Integer value1, DeploymentLocationLocationCode value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeploymentLocationRecord
     */
    public DeploymentLocationRecord() {
        super(DeploymentLocation.DEPLOYMENT_LOCATION);
    }

    /**
     * Create a detached, initialised DeploymentLocationRecord
     */
    public DeploymentLocationRecord(Integer customerId, DeploymentLocationLocationCode locationCode, LocalDateTime createdDate, LocalDateTime lastUpdatedTime) {
        super(DeploymentLocation.DEPLOYMENT_LOCATION);

        setCustomerId(customerId);
        setLocationCode(locationCode);
        setCreatedDate(createdDate);
        setLastUpdatedTime(lastUpdatedTime);
    }
}
