/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables.records;


import hms.commons.rnm.db.schema.tables.ModuleDependency;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleDependencyRecord extends UpdatableRecordImpl<ModuleDependencyRecord> implements Record5<Integer, Integer, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>module_dependency.module_id</code>.
     */
    public void setModuleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>module_dependency.module_id</code>.
     */
    public Integer getModuleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>module_dependency.dependant_module_id</code>.
     */
    public void setDependantModuleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>module_dependency.dependant_module_id</code>.
     */
    public Integer getDependantModuleId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>module_dependency.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>module_dependency.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>module_dependency.last_updated_time</code>.
     */
    public void setLastUpdatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>module_dependency.last_updated_time</code>.
     */
    public LocalDateTime getLastUpdatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>module_dependency.id</code>.
     */
    public void setId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>module_dependency.id</code>.
     */
    public Integer getId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ModuleDependency.MODULE_DEPENDENCY.MODULE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ModuleDependency.MODULE_DEPENDENCY.DEPENDANT_MODULE_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ModuleDependency.MODULE_DEPENDENCY.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ModuleDependency.MODULE_DEPENDENCY.LAST_UPDATED_TIME;
    }

    @Override
    public Field<Integer> field5() {
        return ModuleDependency.MODULE_DEPENDENCY.ID;
    }

    @Override
    public Integer component1() {
        return getModuleId();
    }

    @Override
    public Integer component2() {
        return getDependantModuleId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdatedTime();
    }

    @Override
    public Integer component5() {
        return getId();
    }

    @Override
    public Integer value1() {
        return getModuleId();
    }

    @Override
    public Integer value2() {
        return getDependantModuleId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdatedTime();
    }

    @Override
    public Integer value5() {
        return getId();
    }

    @Override
    public ModuleDependencyRecord value1(Integer value) {
        setModuleId(value);
        return this;
    }

    @Override
    public ModuleDependencyRecord value2(Integer value) {
        setDependantModuleId(value);
        return this;
    }

    @Override
    public ModuleDependencyRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public ModuleDependencyRecord value4(LocalDateTime value) {
        setLastUpdatedTime(value);
        return this;
    }

    @Override
    public ModuleDependencyRecord value5(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModuleDependencyRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleDependencyRecord
     */
    public ModuleDependencyRecord() {
        super(ModuleDependency.MODULE_DEPENDENCY);
    }

    /**
     * Create a detached, initialised ModuleDependencyRecord
     */
    public ModuleDependencyRecord(Integer moduleId, Integer dependantModuleId, LocalDateTime createdDate, LocalDateTime lastUpdatedTime, Integer id) {
        super(ModuleDependency.MODULE_DEPENDENCY);

        setModuleId(moduleId);
        setDependantModuleId(dependantModuleId);
        setCreatedDate(createdDate);
        setLastUpdatedTime(lastUpdatedTime);
        setId(id);
    }
}
