/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables.records;


import hms.commons.rnm.db.schema.enums.ModuleDeploymentsStatus;
import hms.commons.rnm.db.schema.tables.ModuleDeployments;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleDeploymentsRecord extends UpdatableRecordImpl<ModuleDeploymentsRecord> implements Record12<Integer, Integer, String, Integer, String, LocalDate, String, String, Integer, LocalDateTime, LocalDateTime, ModuleDeploymentsStatus> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>module_deployments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>module_deployments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>module_deployments.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>module_deployments.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>module_deployments.deployment_location</code>.
     */
    public void setDeploymentLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>module_deployments.deployment_location</code>.
     */
    public String getDeploymentLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>module_deployments.module_id</code>.
     */
    public void setModuleId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>module_deployments.module_id</code>.
     */
    public Integer getModuleId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>module_deployments.version_no</code>.
     */
    public void setVersionNo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>module_deployments.version_no</code>.
     */
    public String getVersionNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>module_deployments.applied_date</code>.
     */
    public void setAppliedDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>module_deployments.applied_date</code>.
     */
    public LocalDate getAppliedDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>module_deployments.applied_by</code>.
     */
    public void setAppliedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>module_deployments.applied_by</code>.
     */
    public String getAppliedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>module_deployments.comments</code>.
     */
    public void setComments(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>module_deployments.comments</code>.
     */
    public String getComments() {
        return (String) get(7);
    }

    /**
     * Setter for <code>module_deployments.previous_mod_deployment_id</code>.
     */
    public void setPreviousModDeploymentId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>module_deployments.previous_mod_deployment_id</code>.
     */
    public Integer getPreviousModDeploymentId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>module_deployments.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>module_deployments.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>module_deployments.last_updated_time</code>.
     */
    public void setLastUpdatedTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>module_deployments.last_updated_time</code>.
     */
    public LocalDateTime getLastUpdatedTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>module_deployments.status</code>.
     */
    public void setStatus(ModuleDeploymentsStatus value) {
        set(11, value);
    }

    /**
     * Getter for <code>module_deployments.status</code>.
     */
    public ModuleDeploymentsStatus getStatus() {
        return (ModuleDeploymentsStatus) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, String, Integer, String, LocalDate, String, String, Integer, LocalDateTime, LocalDateTime, ModuleDeploymentsStatus> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, String, Integer, String, LocalDate, String, String, Integer, LocalDateTime, LocalDateTime, ModuleDeploymentsStatus> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.CUSTOMER_ID;
    }

    @Override
    public Field<String> field3() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.DEPLOYMENT_LOCATION;
    }

    @Override
    public Field<Integer> field4() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.MODULE_ID;
    }

    @Override
    public Field<String> field5() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.VERSION_NO;
    }

    @Override
    public Field<LocalDate> field6() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.APPLIED_DATE;
    }

    @Override
    public Field<String> field7() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.APPLIED_BY;
    }

    @Override
    public Field<String> field8() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.COMMENTS;
    }

    @Override
    public Field<Integer> field9() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.PREVIOUS_MOD_DEPLOYMENT_ID;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.LAST_UPDATED_TIME;
    }

    @Override
    public Field<ModuleDeploymentsStatus> field12() {
        return ModuleDeployments.MODULE_DEPLOYMENTS.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCustomerId();
    }

    @Override
    public String component3() {
        return getDeploymentLocation();
    }

    @Override
    public Integer component4() {
        return getModuleId();
    }

    @Override
    public String component5() {
        return getVersionNo();
    }

    @Override
    public LocalDate component6() {
        return getAppliedDate();
    }

    @Override
    public String component7() {
        return getAppliedBy();
    }

    @Override
    public String component8() {
        return getComments();
    }

    @Override
    public Integer component9() {
        return getPreviousModDeploymentId();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component11() {
        return getLastUpdatedTime();
    }

    @Override
    public ModuleDeploymentsStatus component12() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCustomerId();
    }

    @Override
    public String value3() {
        return getDeploymentLocation();
    }

    @Override
    public Integer value4() {
        return getModuleId();
    }

    @Override
    public String value5() {
        return getVersionNo();
    }

    @Override
    public LocalDate value6() {
        return getAppliedDate();
    }

    @Override
    public String value7() {
        return getAppliedBy();
    }

    @Override
    public String value8() {
        return getComments();
    }

    @Override
    public Integer value9() {
        return getPreviousModDeploymentId();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value11() {
        return getLastUpdatedTime();
    }

    @Override
    public ModuleDeploymentsStatus value12() {
        return getStatus();
    }

    @Override
    public ModuleDeploymentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value2(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value3(String value) {
        setDeploymentLocation(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value4(Integer value) {
        setModuleId(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value5(String value) {
        setVersionNo(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value6(LocalDate value) {
        setAppliedDate(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value7(String value) {
        setAppliedBy(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value8(String value) {
        setComments(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value9(Integer value) {
        setPreviousModDeploymentId(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value10(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value11(LocalDateTime value) {
        setLastUpdatedTime(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord value12(ModuleDeploymentsStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public ModuleDeploymentsRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, LocalDate value6, String value7, String value8, Integer value9, LocalDateTime value10, LocalDateTime value11, ModuleDeploymentsStatus value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleDeploymentsRecord
     */
    public ModuleDeploymentsRecord() {
        super(ModuleDeployments.MODULE_DEPLOYMENTS);
    }

    /**
     * Create a detached, initialised ModuleDeploymentsRecord
     */
    public ModuleDeploymentsRecord(Integer id, Integer customerId, String deploymentLocation, Integer moduleId, String versionNo, LocalDate appliedDate, String appliedBy, String comments, Integer previousModDeploymentId, LocalDateTime createdDate, LocalDateTime lastUpdatedTime, ModuleDeploymentsStatus status) {
        super(ModuleDeployments.MODULE_DEPLOYMENTS);

        setId(id);
        setCustomerId(customerId);
        setDeploymentLocation(deploymentLocation);
        setModuleId(moduleId);
        setVersionNo(versionNo);
        setAppliedDate(appliedDate);
        setAppliedBy(appliedBy);
        setComments(comments);
        setPreviousModDeploymentId(previousModDeploymentId);
        setCreatedDate(createdDate);
        setLastUpdatedTime(lastUpdatedTime);
        setStatus(status);
    }
}
