/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables.records;


import hms.commons.rnm.db.schema.tables.Module;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleRecord extends UpdatableRecordImpl<ModuleRecord> implements Record5<Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>module.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>module.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>module.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>module.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>module.git_location</code>.
     */
    public void setGitLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>module.git_location</code>.
     */
    public String getGitLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>module.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>module.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>module.last_updated_time</code>.
     */
    public void setLastUpdatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>module.last_updated_time</code>.
     */
    public LocalDateTime getLastUpdatedTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Module.MODULE.ID;
    }

    @Override
    public Field<String> field2() {
        return Module.MODULE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Module.MODULE.GIT_LOCATION;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Module.MODULE.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Module.MODULE.LAST_UPDATED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getGitLocation();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component5() {
        return getLastUpdatedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getGitLocation();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value5() {
        return getLastUpdatedTime();
    }

    @Override
    public ModuleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModuleRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ModuleRecord value3(String value) {
        setGitLocation(value);
        return this;
    }

    @Override
    public ModuleRecord value4(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public ModuleRecord value5(LocalDateTime value) {
        setLastUpdatedTime(value);
        return this;
    }

    @Override
    public ModuleRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleRecord
     */
    public ModuleRecord() {
        super(Module.MODULE);
    }

    /**
     * Create a detached, initialised ModuleRecord
     */
    public ModuleRecord(Integer id, String name, String gitLocation, LocalDateTime createdDate, LocalDateTime lastUpdatedTime) {
        super(Module.MODULE);

        setId(id);
        setName(name);
        setGitLocation(gitLocation);
        setCreatedDate(createdDate);
        setLastUpdatedTime(lastUpdatedTime);
    }
}
