/*
 * This file is generated by jOOQ.
 */
package hms.commons.rnm.db.schema.tables;


import hms.commons.rnm.db.schema.DefaultSchema;
import hms.commons.rnm.db.schema.Indexes;
import hms.commons.rnm.db.schema.Keys;
import hms.commons.rnm.db.schema.tables.records.DevReleaseNoteRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevReleaseNote extends TableImpl<DevReleaseNoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dev_release_note</code>
     */
    public static final DevReleaseNote DEV_RELEASE_NOTE = new DevReleaseNote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevReleaseNoteRecord> getRecordType() {
        return DevReleaseNoteRecord.class;
    }

    /**
     * The column <code>dev_release_note.id</code>.
     */
    public final TableField<DevReleaseNoteRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>dev_release_note.tag_id</code>.
     */
    public final TableField<DevReleaseNoteRecord, Integer> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>dev_release_note.customer_id</code>.
     */
    public final TableField<DevReleaseNoteRecord, Integer> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>dev_release_note.release_by</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> RELEASE_BY = createField(DSL.name("release_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>dev_release_note.release_date</code>.
     */
    public final TableField<DevReleaseNoteRecord, LocalDate> RELEASE_DATE = createField(DSL.name("release_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>dev_release_note.apply_on_top_of_version</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> APPLY_ON_TOP_OF_VERSION = createField(DSL.name("apply_on_top_of_version"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>dev_release_note.dependant_version</code>.
     */
    public final TableField<DevReleaseNoteRecord, JSON> DEPENDANT_VERSION = createField(DSL.name("dependant_version"), SQLDataType.JSON, this, "");

    /**
     * The column <code>dev_release_note.status</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>dev_release_note.feature_summary</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> FEATURE_SUMMARY = createField(DSL.name("feature_summary"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.build_instructions</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> BUILD_INSTRUCTIONS = createField(DSL.name("build_instructions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.fixed_bugs</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> FIXED_BUGS = createField(DSL.name("fixed_bugs"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.known_issues</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> KNOWN_ISSUES = createField(DSL.name("known_issues"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.deployment_details</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> DEPLOYMENT_DETAILS = createField(DSL.name("deployment_details"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.areas_to_be_tested</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> AREAS_TO_BE_TESTED = createField(DSL.name("areas_to_be_tested"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.reference_docs</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> REFERENCE_DOCS = createField(DSL.name("reference_docs"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_release_note.created_date</code>.
     */
    public final TableField<DevReleaseNoteRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dev_release_note.last_updated_time</code>.
     */
    public final TableField<DevReleaseNoteRecord, LocalDateTime> LAST_UPDATED_TIME = createField(DSL.name("last_updated_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dev_release_note.type</code>.
     */
    public final TableField<DevReleaseNoteRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255), this, "");

    private DevReleaseNote(Name alias, Table<DevReleaseNoteRecord> aliased) {
        this(alias, aliased, null);
    }

    private DevReleaseNote(Name alias, Table<DevReleaseNoteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>dev_release_note</code> table reference
     */
    public DevReleaseNote(String alias) {
        this(DSL.name(alias), DEV_RELEASE_NOTE);
    }

    /**
     * Create an aliased <code>dev_release_note</code> table reference
     */
    public DevReleaseNote(Name alias) {
        this(alias, DEV_RELEASE_NOTE);
    }

    /**
     * Create a <code>dev_release_note</code> table reference
     */
    public DevReleaseNote() {
        this(DSL.name("dev_release_note"), null);
    }

    public <O extends Record> DevReleaseNote(Table<O> child, ForeignKey<O, DevReleaseNoteRecord> key) {
        super(child, key, DEV_RELEASE_NOTE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEV_RELEASE_NOTE_TAG_ID);
    }

    @Override
    public Identity<DevReleaseNoteRecord, Integer> getIdentity() {
        return (Identity<DevReleaseNoteRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DevReleaseNoteRecord> getPrimaryKey() {
        return Keys.KEY_DEV_RELEASE_NOTE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DevReleaseNoteRecord>> getKeys() {
        return Arrays.<UniqueKey<DevReleaseNoteRecord>>asList(Keys.KEY_DEV_RELEASE_NOTE_PRIMARY);
    }

    @Override
    public List<ForeignKey<DevReleaseNoteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DevReleaseNoteRecord, ?>>asList(Keys.DEV_RELEASE_NOTE_IBFK_1);
    }

    public ModuleTag moduleTag() {
        return new ModuleTag(this, Keys.DEV_RELEASE_NOTE_IBFK_1);
    }

    @Override
    public DevReleaseNote as(String alias) {
        return new DevReleaseNote(DSL.name(alias), this);
    }

    @Override
    public DevReleaseNote as(Name alias) {
        return new DevReleaseNote(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DevReleaseNote rename(String name) {
        return new DevReleaseNote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DevReleaseNote rename(Name name) {
        return new DevReleaseNote(name, null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Integer, Integer, Integer, String, LocalDate, String, JSON, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }
}
